### ISSUE TITLE
Timeout causing node-red to restart

### ISSUE THREAD

**Issue by nygma2004** [i8beef/node-red-contrib-castv2#14]
I am running cast 2.0.1. I can see that node-red is still getting restarted every 2-3 days. I see the following lines in the log:
```
Feb  6 03:57:09 OpenHAB Node-RED[1838]: 6 Feb 03:57:09 - [red] Uncaught Exception:
Feb  6 03:57:09 OpenHAB Node-RED[1838]: 6 Feb 03:57:09 - Error: Device timeout
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at fn.ontimeout (/home/pi/.node-red/node_modules/castv2-client/lib/senders/platform.js:56:26)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at Object.onceWrapper (events.js:286:20)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at fn.emit (events.js:198:13)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at Timeout.ontimeout [as _onTimeout] (/home/pi/.node-red/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at ontimeout (timers.js:436:11)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at tryOnTimeout (timers.js:300:5)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at listOnTimeout (timers.js:263:5)
Feb  6 03:57:09 OpenHAB Node-RED[1838]: at Timer.processTimers (timers.js:223:10)
Feb  6 03:57:09 OpenHAB systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
Feb  6 03:57:09 OpenHAB systemd[1]: Unit nodered.service entered failed state.
Feb  6 03:57:09 OpenHAB systemd[1]: nodered.service holdoff time over, scheduling restart.
```

**Comment by i8beef** [comment]
Just pushed a new version that should make sure this emit is covered. Look for 2.0.2
