### ISSUE TITLE
Failed to install: node-red-contrib-castv2

### ISSUE THREAD

**Issue by did57** [i8beef/node-red-contrib-castv2#19]
Hi,

node-red-contrib-castv2 does not want to settle with me.
Here is the log:

-----------------------------------------------------------
2020-03-29T13:03:47.197Z Install : node-red-contrib-castv2 2.0.5

2020-03-29T13:03:47.217Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-castv2@2.0.5
2020-03-29T13:03:55.317Z [out] 
2020-03-29T13:03:55.317Z [out] > protobufjs@6.8.9 postinstall /root/.node-red/node_modules/protobufjs
2020-03-29T13:03:55.317Z [out] > node scripts/postinstall
2020-03-29T13:03:55.317Z [out] 
2020-03-29T13:03:55.463Z [err] internal/modules/cjs/loader.js:985
2020-03-29T13:03:55.463Z [err]   throw err;
2020-03-29T13:03:55.463Z [err]   ^
2020-03-29T13:03:55.463Z [err] 
2020-03-29T13:03:55.463Z [err] Error: Cannot find module '/root/.node-red/node_modules/protobufjs/scripts/postinstall'
2020-03-29T13:03:55.463Z [err]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
2020-03-29T13:03:55.463Z [err]     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
2020-03-29T13:03:55.463Z [err]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
2020-03-29T13:03:55.463Z [err]     at internal/main/run_main_module.js:18:47 {
2020-03-29T13:03:55.463Z [err]   code: 'MODULE_NOT_FOUND',
2020-03-29T13:03:55.463Z [err]   requireStack: []
2020-03-29T13:03:55.463Z [err] }
2020-03-29T13:03:55.919Z [err] npm
2020-03-29T13:03:55.919Z [err]  ERR! code ELIFECYCLE
2020-03-29T13:03:55.919Z [err] npm 
2020-03-29T13:03:55.919Z [err] ERR! 
2020-03-29T13:03:55.919Z [err] errno 1
2020-03-29T13:03:55.921Z [err] npm 
2020-03-29T13:03:55.922Z [err] ERR! protobufjs@6.8.9 postinstall: `node scripts/postinstall`
2020-03-29T13:03:55.922Z [err] npm ERR! Exit status 1
2020-03-29T13:03:55.922Z [err] npm 
2020-03-29T13:03:55.922Z [err] ERR! 
2020-03-29T13:03:55.922Z [err] npm 
2020-03-29T13:03:55.922Z [err] ERR! Failed at the protobufjs@6.8.9 postinstall script.
2020-03-29T13:03:55.922Z [err] npm ERR!
2020-03-29T13:03:55.922Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-03-29T13:03:55.948Z [err] 
2020-03-29T13:03:55.948Z [err] npm ERR! A complete log of this run can be found in:
2020-03-29T13:03:55.948Z [err] npm ERR!
2020-03-29T13:03:55.948Z [err]      /root/.npm/_logs/2020-03-29T13_03_55_930Z-debug.log
2020-03-29T13:03:55.961Z rc=1

**Comment by i8beef** [comment]
Im not actually sure what you're seeing here. You might try asking in this issue for protobuff to see if they have any ideas:

https://github.com/protobufjs/protobuf.js/issues/877
