### ISSUE TITLE
Crashing Node-RED

### ISSUE THREAD

**Issue by Botched1** [i8beef/node-red-contrib-castv2#2]
I've seen 5-6 times now that my whole Node-Red docker crashes. At the time of the crash I see this in the log, which seems to point to this:

25 Sep 02:51:04 - [red] Uncaught Exception:
25 Sep 02:51:04 - TypeError: Cannot read property 'close' of null
at PlatformSender.close (/data/node_modules/castv2-client/lib/senders/platform.js:66:15)
at PlatformSender.CastV2SenderNode.onError (/data/node_modules/node-red-contrib-castv2/castv2-sender.js:25:25)
at emitOne (events.js:116:13)
at PlatformSender.emit (events.js:211:7)
at fn.ontimeout (/data/node_modules/castv2-client/lib/senders/platform.js:56:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at fn.emit (events.js:208:7)
at Timeout.ontimeout [as _onTimeout] (/data/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
at ontimeout (timers.js:498:11)

**Comment by i8beef** [comment]
Im not sure why Im not getting notifications for this repo when people post issues... I just published a new version that should make the onError event more resilient when something happens before the node actually is fully instantiated.

**Comment by i8beef** [comment]
Closing for inactivity.
