### ISSUE TITLE
Restarting Google Nest Mini kills Node Red

### ISSUE THREAD

**Issue by Einstein2150** [i8beef/node-red-contrib-castv2#51]
`15 Dec 11:28:10 - [red] Uncaught Exception:
15 Dec 11:28:10 - TypeError: Cannot read property 'send' of null
    at Client.send (/home/pi/.node-red/node_modules/castv2/lib/client.js:128:11)
    at Channel.send (/home/pi/.node-red/node_modules/castv2/lib/channel.js:34:12)
    at fn.Controller.send (/home/pi/.node-red/node_modules/castv2-client/lib/controllers/controller.js:28:16)
    at fn.ConnectionController.disconnect (/home/pi/.node-red/node_modules/castv2-client/lib/controllers/connection.js:32:8)
    at SpotifyReceiver.Application.close (/home/pi/.node-red/node_modules/castv2-client/lib/senders/application.js:37:19)
    at SpotifyReceiver.MediaReceiverBase.close (/home/pi/.node-red/node_modules/node-red-contrib-castv2/lib/MediaReceiverBase.js:25:33)
    at SpotifyReceiver.close (/home/pi/.node-red/node_modules/node-red-contrib-castv2/lib/SpotifyReceiver.js:26:39)
    at CastV2SenderNode.unjoin (/home/pi/.node-red/node_modules/node-red-contrib-castv2/castv2-sender.js:422:31)
    at CastV2ConnectionNode.disconnect (/home/pi/.node-red/node_modules/node-red-contrib-castv2/castv2-sender.js:175:46)
    at Client.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-castv2/castv2-sender.js:229:30)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
`

This log says everything  😩

**Comment by i8beef** [comment]
Try 3.2.11. That should add guards around the RECEIVER management that the CONNECTION management already had.

**Comment by i8beef** [comment]
Closing as fixed. If you still have issues, please reopen.
